apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '8'
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: test2
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-deployment
  type: LoadBalancer
