apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '8'
  labels:
    app: api-app
    app.kubernetes.io/instance: api-app
  name: api-app
  namespace: api-app
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-app
  type: LoadBalancer
