name: OpenShift Tools Installer
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
          helm: latest
